### ISSUE TITLE
Invalid name for the plugin

### ISSUE THREAD

**Issue by mlaitinen** [koodaamo/banking.statements.nordea#2]
When calling `ofxstatement list-plugins`, the Nordea plugin shows up as:
```
$ ofxstatement list-plugins
The following plugins are available: 

  nordea           Suomen Osuuspankki / Finnish Osuuspankki

```

and the only occurrence I could find was the following:

https://github.com/koodaamo/banking.statements.nordea/blob/a7c8f4c57b0c337365f92a20c25fcf07493fbe98/banking/statements/nordea/plugin.py#L21

**Comment by petri** [comment]
Thanks for bringing that up. Fixed in ff77574.
